### PR TITLE
Release 7.0.0

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@conda-forge/core I guess that the equivalent to resetting the build number to 0 is not to reset it to 1000?

**Comment by CJ-Wright** [comment]
When a package has been migrated to the new compilers the build number should be set to 1000 for the `reset build number` part.

**Comment by SylvainCorlay** [comment]
Ping @noloader , @jcfr - this is the conda recipe for the latest cryptopp, making use of cryptopp-cmake. Comments welcome!

**Comment by jcfr** [comment]
Hi Sylvain,

I am out of the office for the next two weeks. I will have a look when I am
back.


Jc

**Pull request merged**
